# Hyperparameters
dataset: "phoenix"
reverse: false
epochs: 500
batch_size: 32
lr: 1e-4
eps: 1e-9
weight_decay: 0
label_smoothing: 0

# Model settings
d_model: 512
hidden_size: 2048
heads: 8
num_encoders: 2
num_decoders: 2
dropout: 0.1
norm_first: False

# Model save and load paths
model_name: "gloss_to_german"
save_path: "src/ml/saved_models"