model:
  num_encoders: 3
  num_decoders: 3
  pretrained_embedding: "efficientnet_b0"

  d_model: 512
  hidden_size: 1024
  num_heads: 8
  dropout: 0.3

training:
  # Basic hyperparameters
  epochs: 100
  batch_size: 8
  lr: 1e-3
  weight_decay: 5e-4
  save_every: 25
  validate_every: 1

  # File path locations
  save_path: 'models'
  file_name: 'best5'
  load_path: 'src/ml/saved_models/epoch_75.pt'
  diagram_path: 'src/ml/reports/figures'

  # Weights used for joint loss
  recognition_weight: 1.0
  translation_weight: 1.0
  
  # Random splitting seed and ration
  use_already_split_sets: True
  seed: 29
  split: [0.8, 0.1, 0.1]

  # Early Stopping
  patience: 8
  delta: 0.01

  # Scheduler
  T_max: 10

  # Gradient clipping
  max_norm: 1.0
    
  # Misc.
  num_workers: 4
  
  # Dataset
  sampling_ratio: 2
  masking_ratio: 0.9
  random_sampling: True
  random_masking: True
  

testing:
  load_path: 'models/epoch_75.pt'
  beam_search: false